# global
CONFIG_FILE = 'config.json'
LOG_FILE = 'log.log'

# okex contract type
SWAP = 'SWAP'
FUTURE = 'FUTURE'

# okex instrument_id
# XBTUSDTM
BTC_USDT_SWAP = 'BTC-USDT-SWAP'
# XBTUSDM
BTC_USD_SWAP = 'BTC-USD-SWAP'
# XBTMM20
BTC_USD_200626 = 'BTC-USD-200626'
# XBTMU20
BTC_USD_200925 = 'BTC-USD-200925'
